# Generated by Django 2.0.1 on 2018-06-04 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStroke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_times_keydowns', models.TextField()),
                ('login_times_keydowns_and_ups', models.TextField()),
                ('password_times_keydowns', models.TextField()),
                ('password_times_keydowns_and_ups', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Login'), (2, 'Password')])),
                ('is_temporary', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
