# Generated by Django 2.0.1 on 2018-06-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keystroke',
            name='type',
        ),
    ]
