# Generated by Django 2.0.1 on 2018-06-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0002_remove_keystroke_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='keystroke',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
