# Generated by Django 2.0.1 on 2018-06-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0004_mouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='timestamps',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
