# Generated by Django 2.0.1 on 2018-06-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_server', '0005_mouse_timestamps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouse',
            old_name='x_pos',
            new_name='cor_pos',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='y_pos',
        ),
    ]
